START TRANSACTION;

INSERT INTO users (
    id,
    username,
    password,
    role,
    avatar,
    theme_primary_color,
    theme_secondary_color
) VALUES
(
    20,
    'kaya_rinha',
    '$2y$12$QmHq.PKv0Hl5BkpUC9QxV.W/alaYMpSXKiOhz7lTwG2eE34rcNUUO',
    'student',
    NULL,
    '#5A3FA8',
    '#C9B8FF'
),
(
    21,
    'aoi_nadeshiko',
    '$2y$12$g5ootjrJMeaCtp9ZWUX8wOwAuvYBVzr8DU3vDxFt.IjLYZEttQnoS',
    'student',
    NULL,
    '#4A90E2',
    '#BFDFFF'
),
(
    22,
    'shirakusa_shion',
    '$2y$12$tglZ7TVHnxZa0tQKyfqAzO/NWIbMborx0BqUEbPSYiMDan5/4jdnO',
    'student',
    NULL,
    '#8E6BBE',
    '#D8C8F0'
),
(
    23,
    'shirakusa_gekka',
    '$2y$12$0p9NoSH4niqqlA/2D1R9p.yyTUKD5Lca88U1VQcc.FSnQpJOsEfKC',
    'student',
    NULL,
    '#1E2A44',
    '#C7D3E8'
);

INSERT INTO students (
    user_id,
    name,
    name_jp,
    birthday,
    zodiac,
    blood_type,
    height,
    weight,
    three_size,
    hometown,
    hobbies,
    special_skill,
    school_year,
    `rank`,
    vocal,
    dance,
    visual,
    bio,
    producer_id,
    producer_status
) VALUES
(
    20,
    'Kaya Rinha',
    '賀陽 燐羽',
    '2000-12-12',
    'Sagittarius',
    'AB',
    162,
    47,
    '78/56/80',
    'Unknown',
    'Quiet training, observing other idols, reading fan letters',
    'Leadership, precise performance control, calm stage presence',
    'Class 1-3',
    'Debut',
    88,
    76,
    92,
    'Former leader of the middle-school No.1 unit SyngUp!. She was once connected to Hatsuboshi Academy, but later became a rival idol associated with 961 Production and Gokutsuki Academy. Birthday, blood type, height, weight, three size, hobbies, and stats are fan-made placeholder values based on her character image.',
    NULL,
    'unassigned'
),
(
    21,
    'Aoi Nadeshiko',
    '藍井 撫子',
    '2000-05-18',
    'Taurus',
    'A',
    158,
    46,
    '77/56/80',
    'Unknown',
    'Fashion, beauty care, social media, collecting luxury accessories',
    'Self-promotion, charming fans, elegant posing',
    'Class 1-3',
    'Debut',
    72,
    78,
    90,
    'A first-year idol from Gokutsuki Academy. She is a B-rank idol from the upper level of the school. She gained many fans by using the power of her wealthy family and has overwhelming confidence in her appearance. She admires Shirakusa Shion and calls her onee-sama, but does not realize she is being used. Birthday, blood type, height, weight, three size, hobbies, and stats are fan-made placeholder values.',
    NULL,
    'unassigned'
),
(
    22,
    'Shirakusa Shion',
    '白草 四音',
    '2000-09-04',
    'Virgo',
    'AB',
    160,
    47,
    '78/56/81',
    'Unknown',
    'Tea, strategy games, observing rivals, acting polite',
    'All-round performance, manipulation, perfect idol mask',
    'Class 1-3',
    'Debut',
    92,
    91,
    94,
    'A first-year idol from Gokutsuki Academy. She reigns as an A-rank idol, with first-class ability in vocal, visual, and dance. She usually acts gentle and polite, but her true nature is cold and ruthless. For her, idols are a means and fans are tools. Birthday, blood type, height, weight, three size, hobbies, and stats are fan-made placeholder values.',
    NULL,
    'unassigned'
),
(
    23,
    'Shirakusa Gekka',
    '白草 月花',
    '2000-11-21',
    'Scorpio',
    'O',
    168,
    52,
    '84/58/86',
    'Unknown',
    'Overseas travel, night views, performance analysis, quiet places',
    'Top-level stage presence, cool performance, international appeal',
    'Class 3-2',
    'Debut',
    96,
    94,
    98,
    'A third-year idol from Gokutsuki Academy. She is the only known S-rank idol in the school and is already famous as a top idol, currently active mainly in America. She dislikes waste, has little interest in most people, and only remembers the names of those with talent. Birthday, blood type, height, weight, three size, hobbies, and stats are fan-made placeholder values.',
    NULL,
    'unassigned'
);

COMMIT;